# Built with Jekyll 3.2.0

# Setup
title:               microTK
tagline:             'A tiny JavaScript library.'
description:         ''
url:                 'http://microtk.io/'
baseurl:             ''

# About/contact
author:
  name:              Todd Henderson
  url:               http://todd-henderson.me
  email:             todd@todd-henderson.me

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Code Syntac Highlighter
highlighter: rouge

# Markdown specs
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo

# Custom vars
version:             v0.0.1-pre

# Exclusions from the final site
exclude: [optional, vendor]


